#%RAML 1.0
title: MuleSoft IDP Universal REST Connector
version: v1

documentation:
 - title: Why?
   content: |
     ### Welcome to MuleSoft IDP Universal REST Connector

 - title: Who?
   content: |
     ### Welcome to MuleSoft IDP Universal REST Connector
      | Author            | Date     | Price |
      | :---------------- | :------: | ----: |
      | Python Hat        |   True   | 23.99 |
      | SQL Hat           |   True   | 23.99 |
      | Codecademy Tee    |  False   | 19.99 |
      | Codecademy Hoodie |  False   | 42.99 |

 - title: How?
   content: |
     ### Welcome to MuleSoft IDP Universal REST Connector

description: |
  ### MuleSoft IDP Universal REST Connector
  | Author | Date | Description
  | -------- | ------- | ------- |
  | G.Jeffcock | 23rd June 2024 || 
  |||| 
  |||| 

baseUri: https://idp-rt.{region}.anypoint.mulesoft.com/api/{platform-api-version}/organizations/{orgId}
baseUriParameters:
  region:
    type: field-runtimeRegion
    required: true
  platform-api-version:
    type: field-platformApiVersion
    required: true
  orgId:
    type: field-orgId
    required: true


mediaType: [ multipart/form-data, application/json ]

protocols:
  - HTTPS

securedBy:
  -   mulesoft-connectedApp-oauth

uses:
  rest-connect: exchange_modules/org.mule.connectivity/rest-connect-library/1.0.2/rest-connect-library.raml


/actions/{action-id}/versions/{action-version}/executions:
  uriParameters:
    action-id:
      type: field-actionId
    action-version:
      type: field-actionVersion

  post:
    displayName: IDP - postDocumentActionExecution
    description:
    body:
      multipart/form-data:
        description: 
        properties:
          callback: # Optional
            (rest-connect.partName): callback
            (rest-connect.partContentType): application/json
            type: callback
            required: false
          file:
            (rest-connect.partName): file     
            (rest-connect.partContentType): application/octet-stream
            (rest-connect.partFilenameParameter): filename
            description: |
                    **Accepted File Formats**: PDF, PNG, JPG (150 DPI or more recommended).
                    **File Size Limits**: 10MB
            type: file
            fileTypes:
              - image/jpeg
              - image/png
              - application/pdf
            minLength: 1
            maxLength: 10485760
            required: true
        additionalProperties: false

    responses:
      201:
        headers:
          Content-Type:
            description:
        description: Created
        body:
          application/json: DocumentExecutionPost
      400:
        headers:
          Content-Type:
            description:
        description: Bad Request
        body:
          application/problem+json:
            type: object-commonError
      406:
        headers:
           Content-Type:
             description:
        description: Not Acceptable
        body:
          application/problem+json:
            type: object-commonError
      500:
        headers:
           Content-Type:
             description:
        description: Internal Server Error
        body:
          application/problem+json:
            type: object-commonError

  /{execution-id}:
    uriParameters:
      execution-id:
        type: field-executionId
    get:
      displayName: IDP - getDocumentActionExecution
      description:
      queryParameters:
        valueOnly:
          description:
          type: field-valueOnly
          required: false
      responses:
        200:
          headers:
            Content-Type:
              description:
          description: Success
          body:
            application/json: DocumentExecutionGet
        404:
          headers:
            Content-Type:
              description:
          description: Not Found
          body:
            application/problem+json:
              type: object-commonError
        406:
          headers:
            Content-Type:
              description:
          description: Not Acceptable
          body:
            application/problem+json:
              type: object-commonError
        429:
          headers:
            Content-Type:
              description:
          description: Too Many Requests
          body:
            application/problem+json:
              type: object-commonError

securitySchemes:
  mulesoft-connectedApp-oauth:
    type: OAuth 2.0
    description: |
        ### [Configure Connected Apps](https://docs.mulesoft.com/idp/automate-document-processing-with-the-idp-api#create-a-connected-app)

        ```
          curl --location --request POST 'https://anypoint.mulesoft.com/accounts/api/v2/oauth2/token' \ 
          --header 'Content-Type: application/json' \
          --data-raw '{
            "grant_type": "client_credentials",
            "client_id": "<connected-app-client-id>", 
            "client_secret": "<connected-app-client-secret>" 
          }'
        ```
    settings:
      accessTokenUri: https://anypoint.mulesoft.com/accounts/api/v2/oauth2/token
      authorizationGrants:
        - client_credentials
    describedBy:
      headers:
        Authorization:
          description: |
            Used to send a valid OAuth 2 access token. Bearer 234235246236236326
          type: string
          example: Bearer 0695bab3-e776-4d33-b61d-092789cb8765
          pattern: ^Bearer [{]?[0-9a-fA-F]{8}-([0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}[}]?$
      responses:
        401:
          headers:
            Content-Type:
              description:
          description: |
            Bad or expired token. This can happen if the API consumer uses a revoked or expired access token. To fix, you should re-authenticate the user.
          body:
            application/problem+json:
              type: object-commonError
        403:
          headers:
            Content-Type:
              description:
          description: |
            Bad OAuth request (wrong consumer key, bad nonce, expired timestamp...). Unfortunately, re-authenticating the user won't help here.
          body:
            application/problem+json:
              type: object-commonError


types:

  callback:
    description: Optional Callback https://docs.mulesoft.com/idp/automate-document-processing-with-the-idp-api#callback-url 
    properties:
      noAuthUrl:
        description: Your Callback URL to be used by IDP which can include query params
        example: https://yourCallbackURL.com?youCanUseQueryParms=SomeGreatValue&apikey=43243442342424
        type: string
    additionalProperties: false

  field-valueOnly:
    description: Un-supported so use with Caution - Return Confidence levels when set to false
    type: boolean
    example: false

  field-runtimeRegion:
    displayName: IDP Runtime Region
    description: |
      Currently supported IDP Runtime Regions
      - us-east-1
      - eu-central-1
    type: string
    enum:
      - us-east-1
      - eu-central-1
    default: us-east-1
    pattern: ^[a-z]{2}-[a-z]+-\d+$

  field-platformApiVersion:
    displayName: IDP Platform API Version
    description: Current version of the MuleSoft IDP Platform API
    type: string
    enum:
      - v1
    default: v1
    maxLength: 2
    minLength: 2
    pattern: ^v[0-9]$
  field-orgId:
    displayName: MuleSoft Anypoint Organization Id
    description: |
      Your Anypoint Organisation Id see: [Find your Organization ID.](https://docs.mulesoft.com/access-management/organization#find-your-organization-id)
    example: eca25329-9592-4ff1-9054-1b08d103b991
    pattern: ^[{]?[0-9a-fA-F]{8}-([0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}[}]?$
  field-actionId:
    displayName: IDP Document Action Id
    description: Published Document Action UUID
    default: 90c3e286-72b5-42ca-92d0-22f86ea8d766
    example: 90c3e286-72b5-42ca-92d0-22f86ea8d766
    type: string
    pattern: ^[{]?[0-9a-fA-F]{8}-([0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}[}]?$
  field-actionVersion:
    displayName: IDP Document Action Id Version
    description: Document Action Version like 1.0.0
    default: 1.1.0
    example: 1.1.0
    type: string
    pattern: ^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9A-Za-z-][0-9A-Za-z-]*)(?:\.(?:0|[1-9A-Za-z-][0-9A-Za-z-]*))*))?(?:\+([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?$
  field-executionId:
    displayName: IDP Execution Id
    description: IDP Execution Id returned after successful submission
    default: 022c61de-9bfc-4a94-8a9c-43c5f8ac153e
    example: 022c61de-9bfc-4a94-8a9c-43c5f8ac153e
    type: string
    pattern: ^[{]?[0-9a-fA-F]{8}-([0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}[}]?$
  field-ExecutionStatus:
    displayName: IDP Status
    description: |
      ## [Execution Results Reference](https://docs.mulesoft.com/idp/automate-document-processing-with-the-idp-api#execution-status-reference).

      When you query the results of an execution, the IDP API returns any of the following statuses:

      - `ACKNOWLEDGED`: The document action execution request was received.
      - `IN_PROGRESS`: The execution started.
      - `RESULTS_PENDING`: The execution finished and IDP is processing the results.
      - `MANUAL_VALIDATION_REQUIRED`: The execution finished but the results need manual validation.
      - `FAILED`: The execution request finished unsuccessfully.
      - `PARTIAL_SUCCESS`: The execution request finished but some sub-tasks failed.
      - `SUCCEEDED`: The execution request finished successfully.
    default: IN_PROGRESS
    enum:
      - ACKNOWLEDGED
      - IN_PROGRESS
      - RESULTS_PENDING
      - MANUAL_VALIDATION_REQUIRED
      - FAILED
      - PARTIAL_SUCCESS
      - SUCCEEDED
    example: IN_PROGRESS
    type: string

  DocumentExecutionPost:
    (rest-connect.default): application/json
    description:
    displayName: Document Action Execution Response
    type: object
    properties:
      id:
        description:
        type: field-executionId
        required: true
      documentName:
        description:
        type: string
        example: IDP-PO-CD656092-BurlingtonTextiles.pdf
        required: true
      status:
        description:
        type: field-ExecutionStatus
        required: false
    additionalProperties: false
    example: {"id": "af78b8b2-3867-4073-aac6-d24e01f48ae2","documentName": "IDP-PO-CD656092-BurlingtonTextiles.pdf"}

  DocumentExecutionGet:
    type: object
    description:
    properties:
      pages?:
        type: array
        items: Page
      id?:
        type: field-executionId
      documentName?:
        type: string
      prompts?:
        type: Prompt
      status?:
        type: field-ExecutionStatus
  Page:
    type: object
    properties:
      tables?:
        type: object
        properties: {}
      page?:
        type: string
      fields?:
        type: object
        properties: {}
      prompts?:
        type: Prompt
  Prompt:
    type: object
    properties:
      answer?: Field
      source?:
        type: string
      prompt?:
        type: string
  Field:
    type: object
    properties:
      value?:
        type: string
      geometry?:
        type: object
        properties:
          height:
            type: number
            required: false
          left:
            type: number
            required: false
          width:
            type: number
            required: false
          top:
            type: number
            required: false
      confidenceScore?:
        type: number

  object-commonError:
    displayName: IDP Common Error Response
    description: IDP Common Error Response
    properties:
      status:
        description: HTTP response status codes
        default: 404
        example: 404
        type: number
        format: int
        required: true
      title:
        description: Error Title
        example: Not Found
        type: string
        required: true
      detail:
        description: Error Details if available
        example: "Action Id: 90c3e286-72b5-42ca-92d0-22f86ea8d766, Version: 1.1.0, Execution Id: 022c61de-9bfc-4a94-8a9c-43c5f8ac1531"
        type: string
        required: false
    example: {"status": 404,"title": "Not Found"}
    additionalProperties: false